# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.IntegerField(verbose_name='Сумма ставки')),
            ],
            options={
                'verbose_name': 'Ставка',
                'verbose_name_plural': 'Ставки',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название лота')),
                ('price', models.BigIntegerField(verbose_name='Цена')),
                ('price_step', models.IntegerField(verbose_name='Шаг цены')),
                ('text', models.TextField(max_length=200, verbose_name='Описание лота')),
                ('status', models.BooleanField(choices=[(True, 'Активный'), (False, 'Завершенный')], default=True, verbose_name='Статус')),
                ('close_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата закрытия')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Лоты',
            },
        ),
        migrations.AddField(
            model_name='bet',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='lotAPP.Lot', verbose_name='Выберите лот для ставки'),
        ),
        migrations.AddField(
            model_name='bet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор ставки'),
        ),
    ]
